# Generated by Django 5.1.3 on 2025-02-03 23:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_inventorypicklist_unique_order_picklist'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryPicklistItemLocations',
            fields=[
                ('auto_id', models.AutoField(primary_key=True, serialize=False)),
                ('inventory_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.inventory')),
                ('picklist_item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.inventorypicklistitem')),
            ],
        ),
    ]
