# Generated by Django 5.1.3 on 2025-04-11 04:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0017_inventorypicklistitem_actual_picked_quantity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorypicklistitem',
            name='picked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='picked_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inventorypicklistitem',
            name='repicked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='repicked_items', to=settings.AUTH_USER_MODEL),
        ),
    ]
