# Generated by Django 5.1.3 on 2025-02-10 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0008_alter_part_sku_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='barcode',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
