name: Django + React CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: postgres.wctpncuvrrotnnzsrroc
          POSTGRES_PASSWORD: BsuKwx5pjWPJ8E8d
          POSTGRES_DB: postgres
        options: >-
          --health-cmd="pg_isready -U postgres"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      # Step 1: Check out the repository
      - name: Check out repository
        uses: actions/checkout@v3

      # Step 2: Set up Python and Install Backend Dependencies
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'

      - name: Install backend dependencies
        working-directory: WarehousePilot_app/backend
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 3: Set up Node.js and Install Frontend Dependencies
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # Adjust this to the Node.js version your frontend requires

      - name: Install frontend dependencies
        working-directory: WarehousePilot_app/frontend
        run: |
          npm install

      # Step 4: Build the React Frontend
      - name: Build frontend
        working-directory: WarehousePilot_app/frontend
        run: |
          npm run build

      # Step 5: Run Backend Migrations
      - name: Run migrations
        working-directory: WarehousePilot_app/backend
        env:
          DATABASE_URL: postgres://postgres.wctpncuvrrotnnzsrroc:BsuKwx5pjWPJ8E8d@aws-0-us-east-1.pooler.supabase.com:6543/postgres
        run: |
          python manage.py migrate

      # Optional: Run Backend Tests
      - name: Run backend tests
        working-directory: WarehousePilot_app/backend
        run: |
          python manage.py test

      # Optional: Run Frontend Tests
      - name: Run frontend tests
        working-directory: WarehousePilot_app/frontend
        run: |
          npm test

