name: Django + React CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: postgres.wctpncuvrrotnnzsrroc

          POSTGRES_PASSWORD: BsuKwx5pjWPJ8E8d
          POSTGRES_DB: postgres
        options: >-
          --health-cmd "pg_isready -U testuser -d testdb"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    # 1. Check out the code
    - name: Checkout code
      uses: actions/checkout@v3

    # 2. Set up Python for Django
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    # 3. Install backend dependencies
    - name: Install Django dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # 4. Wait for PostgreSQL to be ready
    - name: Wait for PostgreSQL to be ready
      run: |
        until pg_isready -h 127.0.0.1 -U testuser -d testdb; do
          echo "Waiting for PostgreSQL...";
          sleep 1;
        done

    # 5. Run Django migrations
    - name: Run migrations
      env:
        DATABASE_URL: postgres://postgres.wctpncuvrrotnnzsrroc:BsuKwx5pjWPJ8E8d@aws-0-us-east-1.pooler.supabase.com:6543/postgres

      run: |
        python manage.py migrate

    # 6. Run Django tests
    - name: Run Django tests
      env:
        DATABASE_URL: postgres://postgres.wctpncuvrrotnnzsrroc:BsuKwx5pjWPJ8E8d@aws-0-us-east-1.pooler.supabase.com:6543/postgres

      run: |
        python manage.py test

    # 7. Set up Node.js for React
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    # 8. Install frontend dependencies
    - name: Install React dependencies
      working-directory: frontend
      run: |
        npm install

    # 9. Run React tests
    - name: Run React tests
      working-directory: frontend
      run: |
        npm test -- --watchAll=false

    # 10. Build React for production
    - name: Build React app
      working-directory: frontend
      run: |
        npm run build
